project 'NetWorkRequest.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NetWorkRequest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NetWorkRequest
  pod 'PPNetworkHelper', '~> 0.4'
  
  target 'NetWorkRequestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetWorkRequestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
